### ISSUE TITLE
Descending order on ⌃⇧P

### ISSUE THREAD

**Issue by romashamin** [romashamin/sort-me-sketch#1]
https://twitter.com/pepelsbey/status/648166406652100608

**Comment by pepelsbey** [comment]
Thanks! But I think toggling sorting order would be better, just like it happens when you click column’s header:

![sort](https://cloud.githubusercontent.com/assets/105274/10130739/2e31ced2-65cb-11e5-8d8e-dea271398e9d.gif)

**Comment by romashamin** [comment]
I really liked the idea of toggling when I heard it from you for the first time. I’ve been thinking about it for a while. There are some points that bothers me.

I’m afraid some users will not figure out the reason why every time the plugin produces different result. It’ll make the plugin kind of unpredictable.

The column’s header in your example is not a good design example. Many people does not understand what does the arrow on the right mean (for instance, I don’t). They use table sorting like “click... uh, that’s not what I wanted... click again... yeah, that’s right.”

@pepelsbey

**Comment by pepelsbey** [comment]
Maybe you could introduce another shortcut that toggles order?
For the ones who are conscious enough to understand what’s goin on.

**Comment by romashamin** [comment]
Beyond doubt it’s possible. But I usually answer ‘No’ to the all ideas that makes me write more code and make the product more complex. I need more time to ponder on it.

P. S. I still can’t see the criteria behind this:
- 1 3 2 → 1 2 3

Is it _If the index of the ‘min’ element is less than index of ‘max’?_

What the result must produce ‘toggler’ for the next examples?
- 2 4 1 3 → ?
- 2 1 4 3 → ?

@pepelsbey

**Comment by pepelsbey** [comment]
> What the result must produce ‘toggler’ for the next examples?

Not sorted? Soft by default. Sorted? Reverse order.
