### ISSUE TITLE
Simply stopped working

### ISSUE THREAD

**Issue by Raghav789** [romashamin/sort-me-sketch#13]
It Simply stopped working! sketch version 42
UPDATE: Now I'm using the 46 version, it's working but, commands were inverted i.e for A1_Z9 it actually does Z9-A1 and vice verse 

![sort](https://user-images.githubusercontent.com/29393153/29516706-11df5c04-868f-11e7-9806-28d8103dc8e3.gif)

**Comment by romashamin** [comment]
@Raghavdesi9ns 

> it's working but, commands were inverted

I guess the plugin works correct, see this issue: https://github.com/romashamin/sort-me-sketch/issues/4
