### ISSUE TITLE
[Feature Request] Reverse Layer Order

### ISSUE THREAD

**Issue by ryanclaytoncodes** [romashamin/sort-me-sketch#14]
Hello. Thanks for a plugin that actually works! Any chance you can also integrate a "Reverse Layer Order" feature. All of the plugins that attempt to do this are broken.

**Comment by collinbrady** [comment]
Would love to see this as well - everything is broken right now. I don't understand why sketch sorts their layers in what seems to be reverse order and didn't included any baked-in tools to change that.

**Comment by romashamin** [comment]
@ryanclaytoncodes @collinbrady sorry, can’t get what you guys are talking about.

Sort Me sorts layers in two ways. Use **⌃⇧O** to sort them this way:

- Layer 3
- Layer 2
- Layer 1

Use **⌃⇧P** to sort opposite:

- Layer 1
- Layer 2
- Layer 3

If shortcuts do not work, check they are not in use by other plugin.

**Comment by kimroen** [comment]
I believe what is asked is if you can have a command to reverse the order of the currently selected layers (no matter what their names are).

So for example:

- Third cell
- Second cell
- First cell copy 2
- First cell

Should turn into:

- First cell
- First cell copy 2
- Second cell
- Third cell

**Comment by romashamin** [comment]
OK, now I got it, thanks!

Of course it is possible. The problem is I have moved to Figma.

Maybe some of you could fork the repo and change `sortLayers` function like this:

```
function reverseOrder(layers) {
  return [[layers reverseObjectEnumerator] allObjects]
}
```
