### ISSUE TITLE
Does not work in Sketch 50.2

### ISSUE THREAD

**Issue by ghost** [romashamin/sort-me-sketch#17]
It just does nothing. :(

**Comment by romashamin** [comment]
@robmosca just checked — everything works fine.

Did you try to run Sort Me form Plugins menu, not with shortcut? Sometimes shortcuts conflict and it looks like the plugin stops running.

**Comment by IonLzr** [comment]
Same here, triggered from menu, does nothing on Sketch 50.2 (55047). 

Thanks!
