### ISSUE TITLE
Compatibility with Sketch 43.1

### ISSUE THREAD

**Issue by Yashrg** [romashamin/sort-me-sketch#9]
Sketch 43 release notes state that Sketch will no longer load and run certain older plugins. Can someone verify compatibility with Sketch 43.1?

**Comment by davemoz** [comment]
Working for me in Sketch 43.2

**Comment by Yashrg** [comment]
Thanks @davemoz. I wanted confirmation for V43+ and after checking with my peers I upgraded sketch. Can confirm this is working for me as well on V43.2
